import React from 'react';
import "../Blogs/Blog.css"

function Blog1(){
    return(
        <>
            <div className="container-fluid">
                <div className="row">
                    <div className="col-10 mx-auto">
                        <div className="row">
                        <h1 className = "mx-auto" id="heading">
                    Farmers Protest
            </h1>
            <p id="article"> <span className="tab"></span>Since last 70 days the farmers protest is going on against the three Farmer laws passed by the Central Government on the borders of Delhi. The story of farmers laws is very critical, and many intellectuals have put their thoughts into this, so I won’t be bothering  anyone with my views on these farmer laws, but I am here to present my views on what is happening in India under the skin of farmers protest and is that really needed? So let me give you the quick recap of all these…<br /><br /><span className="tab"></span>
            The farmer agitation started taking heat in Sept’20. The farmers (mainly from Punjab and Haryana) were asking for the removal of the three farm laws passed in parliament and the guarantee of the Minimum Support Price(MSP) for the crops. So, farmers from Punjab repelled these laws in their state and started to march to Delhi to make central government take them back. In way they got support from the farmer leaders from Haryana and they marched to Delhi. In way to Delhi they were blocked by police of Haryana but it was practically impossible to stop huge number o the farmers. Then all the farmers reached Delhi border and farmer leaders seemed permission to continue their protests on Ram Leela maidan which was denied, instead given another location which was further denied by the farmer leaders. So all the farmer leaders decided to stay at the border of Delhi-UP, Delhi-Punjab, Delhi-Haryana, Delhi-Rajasthan. And since then, the farmer protests are going on from the borders of Delhi.<br /><br /><span className="tab"></span>
            This humongous movement is not lead by a single farmer union but it constitutes near about 80 farmer union and hence it is certain that movement has lot of leaders. The major faces among the crowd were Hannan Mollah, Rakesh Tikait, VM Singh, Yogendr Yadav, Media Patkar, Gurunam Singh Chadhuni, Balbir Singh Rajewal and many more. It’s interesting that from first day of the agitation, farmer leaders said that they won’t allow any political leader to get help of our movement and any political activity would not be entertained but most of the leaders are politician themselves and failed more than one time in general elections. Apart from that many arguable instances occurred when this movement was questionable, but the opposition party made such a fuss about all this issue which created a set that asking farmers why the anti-national things are happening under your watch(Mainly regarding Khalistan and the so-called intellectual jailed students) is simply questioning the patriotism and integrity of the farmers, which finally lead to massacre on 26 January. Before that, 11 rounds of unsuccessful conversation happened between Agriculture Minister Mr. Narendra Tomar, Rail Minister Mr. Piyush Goyal from government and all the leaders of Farmers to persuade the farmers about new laws. As the republic day was coming farmer leaders announced that they are going to arrange Tractor March in Delhi on republic day to pressurise the government. And then, everything started falling apart.<br /><br /><span className="tab"></span>
            We all know what happened at Red fort Delhi on 26 January and we are seeing what is happening since then. The damage this march has caused to Farmers movement is unrecoverable. The top leaders of farmer protest are now on radar of police since the law has been broken and its more of a law and order situation than a simple protest.
    In order to gain more support and empathy from public, the opposition parties are showing their support to these leaders.<br /><br /><span className="tab"></span> The recent development in this chapter is the international pop star Rihanna tweeted that the why no one is talking about farmer protest going on in Delhi and the internet ban on border of New Delhi? The infamous environmentalist and human right activist Greta Thunberg and past pornstar Mia Khalifa also showed support to this movement. This became the new issue because the one who supported farmer litigation and other popular celebrity faces in India said that there is no need of international intervention on these issues, India is enough prepared to resolve its own issues. On the contrary side, those who oppose the laws and opposition party claimed the remarks of Rihanna, Mia and Greta were reasonable and government should now think about issue seriously and should take the laws back. But after some time shocking things came into light than this all (Rihanna’s and international figures’ tweets) was planned and it was well planner before month. The screenshot of Google Docs of the Greta Thunberg leaked and with the time and date it was written clearly that hoe the things are going to happen. The recent news is, the case against Greta Thunberg has been filed in Delhi and Mumbai. <br /><br />
            I personally find these all matters, about the 26 jan R. Day violence and the tweets of such infamous personalities are a part of big propaganda or more of a conspiracy against the nation. Since the involvement of Khalistani activism in this movement is not hidden and we all know that the Khalistani activists are mostly located outside of the India and they run their racket remotely. And some of such activists are seen endorsing Rihanna for her tweet. The left front in our country (or in any country except China and Russia to be fair) is involved in every violence held against government. We have witnessed this in anti-CAA protests during last February, Shaheen Bagh- Delhi riots. So it would be mistake to think that the communist parties or their masters are not involved in this. <br /><br /><span className="tab"></span>Now lets talk about what government should do in this place. The government must find all the links of these tweets since the FIR has been filed against Greta, it would make government clear about what are roots of the violence and anti-national propaganda. On the other hand, government should think about how to convince the farmers about these laws because these laws does have strong support among the public and farmers, all across nation and many people believe that these reforms are needed to relieve India’s agriculture sector. Talking about the third side of it, the farmers front, once the moral support by population of nation to any movement is gone, the movement is likely to be dead. The farmers also need to understand that their supporting ground is collapsed after 26 January and there is sentiment against them in part of society. The farmers also need to realise that, blocking the capital of country for unknown time without having any rational discussion or oppose just to amuse some of union leaders is only going to make them look bad in overall sight. The first mistake this protest has done, is to involve anti national elements(knowingly or unknowingly). So without loosing the sanctity of the agitation, farmers also need to rethink their demand or at least start talking rationally about the farmer litigations with government and try to avoid the involvement of people with communist mindset in the protest because those are only reasons which could lead to end of this protest in unintentional ways. <br /><br /><span className="tab"></span>So let's hope that there will be a fair solution next time on the table, acceptable by both the parties and the nation could move on to the other important things.
            </p>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}
export default Blog1;